Adding support to copy the articats into S3 bucket
Signed-off-by: Naresh Paramata <nparamat@qti.qualcomm.com>

diff --git a/.github/workflows/sync_build.yml b/.github/workflows/sync_build.yml
--- a/.github/workflows/sync_build.yml
+++ b/.github/workflows/sync_build.yml
@@ -37,9 +37,9 @@ on:
         default: ${{ github.ref_name }}
 
     outputs:
-      workspace_path:
-        description: "Path of synced workspace"
-        value: ${{ jobs.build.outputs.workspace_path }}
+      s3_location:
+        description: "S3 location of uploaded artifacts"
+        value: ${{ jobs.build.outputs.s3_location }}
 
 jobs:
   build:
@@ -85,3 +85,43 @@ jobs:
           pr_ref: ${{ inputs.pr_ref }}
           pr_repo: ${{ inputs.pr_repo }}
           base_ref: ${{ inputs.base_ref }}
+
+      - name: Create file list for artifacts upload
+        shell: bash
+        run: |
+          workspace=${{ github.workspace }}
+          mkdir -p $workspace/../artifacts
+          touch $workspace/../artifacts/file_list.txt
+          cd $workspace/MINKIPC_LIBS
+          tar -cJf ${{ github.workspace }}/artifacts.tar.xz usr/local
+          echo "${{ github.workspace }}/artifacts.tar.xz" >> $workspace/../artifacts/file_list.txt
+
+      - name: Upload artifacts
+        id: upload-artifacts
+        uses: qualcomm-linux-stg/minkipc/.github/actions/aws_s3_helper@main
+        with:
+          s3_bucket: qli-stg-gen-qlnx-gh-artifacts
+          local_file: ${{ github.workspace }}/../artifacts/file_list.txt
+          mode: multi-upload
+
+      - name: Clean up
+        run: |
+          rm -rf artifacts
+
+      - name: Update summary
+        if: success() || failure()
+        shell: bash
+        run: |
+          if [ ${{ steps.build_workspace.outcome }} == 'success' ]; then
+            echo "Build was successful"
+            summary=":heavy_check_mark: Build Success"
+          else
+            echo "Build failed"
+            summary=":x: Build Failed"
+          fi
+          SUMMARY='
+          <details><summary><i>Build Summary</i></summary>
+          '${summary}'
+          </details>
+          '
+          echo -e "$SUMMARY" >> $GITHUB_STEP_SUMMARY
